### ISSUE TITLE
Add Follow User Functionality

### ISSUE THREAD

**Issue by Bcsotty** [andyblarblar/PersonalPalate#3]
We need a way for the front-end to follow a user. The input would be an email, and the result would be one of the following cases.

Success: The server returns a success message that we can process to inform the user they are now following someone.

Failure: 
1. The server returns a failure message that the user cannot be found
2. The server returns a failure message that the user doesn't allow people to follow them

**Comment by andyblarblar** [comment]
Implimented. I've combined one and two, since otherwise people could spam the endpoint to find the emails of otherwise private users (like the infamous "this password already exsits")
